
export const COURSES_LOADING = 'COURSES_LOADING'
export const ADD_COURSES = 'ADD_COURSES'
export const COURSES_FAILED =  'COURSES_FAILED'


export const SUBJECTS_LOADING = 'SUBJECTS_LOADING'
export const ADD_SUBJECTS = 'ADD_SUBJECTS'
export const SUBJECT_FAILED = 'SUBJECT_FAILED'

export const SYLLABUS_LOADING = 'SYLLABUS_LOADING'
export const ADD_SYLLABUS = 'ADD_SYLLABUS'
export const SYLLABUS_FAILED = 'SYLLABUS_FAILED'


export const CHAPTER_LOADING = 'CHAPTER_LOADING'
export const ADD_CHAPTER = 'ADD_CHAPTER'
export const CHAPTER_FAILED = 'CHAPTER_FAILED'


export const EXERCISE_LOADING = 'EXERCISE_LOADING'
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const EXERCISE_FAILED = 'EXERCISE_FAILED'



export const CODE_COMPILING = 'CODE_COMPILING'
export const ADD_CODE = 'ADD_CODE'
export const CODE_FAILED= 'CODE_FAILED'
